---

cluster_from_name_regex: "^(.+)_.+$"

role_from_name_regex: "^.+_(.+)$"

hosts:

- name: bsa2
  fqdn: bsa2.bsa.broadsoftware.com
  ssh_user: sa
  libvirt_connect: qemu+ssh://sa@bsa2.bsa.broadsoftware.com/system
  system_memory_mb: 2048
  volumes:
  - path: /vol00
    device: /dev/sda1
  - path: /vol01
  - path: /vol02
  - path: /vol03
  - path: /vol04
    
- name: bsa3
  disabled: False
  fqdn: bsa3.bsa.broadsoftware.com
  ssh_user: sa
  libvirt_connect: qemu+ssh://sa@bsa3.bsa.broadsoftware.com/system
  system_memory_mb: 2048
  volumes:
  - path: /vol00
    device: /dev/sda1
  - path: /vol01
  - path: /vol02
  - path: /vol03
  - path: /vol04
    
- name: bsa4
  disabled: False
  fqdn: bsa4.bsa.broadsoftware.com
  ssh_user: sa
  libvirt_connect: qemu+ssh://sa@bsa4.bsa.broadsoftware.com/system
  system_memory_mb: 2048
  volumes:
  - path: /vol00
    device: /dev/sda1
  - path: /vol01
  - path: /vol02
  - path: /vol03
  - path: /vol04
    
    